### ISSUE TITLE
Status of Library

### ISSUE THREAD

**Issue by ppearson111** [brodykenrick/ANTPlus_Arduino#1]
Brody, Hi - I just recently found your repository here.  I'm looking to do a little home-brew ANT+ project with an arduino; wondering if you've done anything as of late with the suggested ANT+ module and if you think it's still a good option for ANT+ tinkering?  I'd mainly like to write a little arduino sketch that will log data from a heart rate monitor.  I have lots of development experience but none with ANT+.  Any info or pointers are greatly appreciated, thanks! -Paul

**Comment by brodykenrick** [comment]
Hi Paul,

It is pretty much perfect for getting the info out of a heart rate monitor.
Or a cadence/distance sensor.

That is exactly what I was using it for. See the random blog I posted on it
- linked from the project that also has the rest of the Arduino stuff that
  does display (on e-ink or 7 segment displays).

I've not done anything recently but this module should just be getting
cheaper.

Cheers,
Brody
