### ISSUE TITLE
off topic

### ISSUE THREAD

**Issue by RobertoMarchese** [brodykenrick/ANTPlus_Arduino#2]
Hi, 
I'm look for the Brody Kenrick who created this redmine patch:

http://projects.andriylesyuk.com/boards/18/topics/141-interest-in-the-ability-to-add-project-s-custom-fields-to-issues-lists-queries

are you? Can I contact you for some information?

Kind Regards

**Comment by brodykenrick** [comment]
Hi Roberto,

That is me. What info are you after?

Cheers,
Brody

**Comment by RobertoMarchese** [comment]
Thanks,
I have applied the patch, and I can see the new columns on the 'columns selector'.
But when I try to apply query with the project fields, this error arise on log file:

ActionView::Template::Error (undefined method `project_cf_1' for #<Issue:0x40431d8>):
    48:     <% if Redmine::VERSION::MAJOR < 2 || Redmine::VERSION::MINOR < 3 || defined?(ChiliProject) %>
    49:     <td class="id"><%= link_to issue.to_param, :controller => 'issues', :action => 'show', :id => issue %></td>
    50:     <% end %>
    51:     <% inline_columns.each do |column| %><%= content_tag 'td', column_content(column, issue), :class => column.respond_to?(:css_classes) ? column.css_classes : column.name %><% end %>
    52:   </tr>
    53:   <% if @query.respond_to?(:block_columns) %>
    54:   <% @query.block_columns.each do |column|
  app/models/query.rb:61:in`value_object'
  app/helpers/queries_helper.rb:86:in `column_content'
  app/helpers/issues_helper.rb:29:in`block in issue_list'
  app/helpers/issues_helper.rb:25:in `each'
  app/helpers/issues_helper.rb:25:in`issue_list'
  app/views/issues/index.html.erb:63:in `_app_views_issues_index_html_erb___130523369_32755896'
  app/controllers/issues_controller.rb:87:in`block (2 levels) in index'
  app/controllers/issues_controller.rb:86:in `index'

**Comment by RobertoMarchese** [comment]
I forget, this is my system configuration:
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p594 (2014-10-27) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Filesystem  
Redmine plugins:
  extended_fields                0.2.3-BK
  project_overview               1.2.0
  projects_tree_view             0.0.8
  redmine_agile                  1.3.5
  redmine_checklists             3.0.2
  sidebar_hide                   0.0.7

**Comment by brodykenrick** [comment]
Hi Roberto,

As i am sure you can see it is complaining about 'project_cf_1'.

This code was a long time ago and in a side project so i don't recall.
We've also decommissioned redmine in my company so i don't have a testing
environment anymore.

I think the work was done against 2.4 so that is the first starting point
I'd look at.
