### ISSUE TITLE
Multi channel

### ISSUE THREAD

**Issue by jerome2710** [brodykenrick/ANTPlus_Arduino#3]
Hi,

I am using the AP2 (ANTAP281M5IB) with the sample code from [Digital Hack Blogspot](http://digitalhacksblog.blogspot.com.au/2012/10/heart-rate-monitor-project-phase-1.html). Is it possible to use your code with multi channel? I am trying to read out some bike sensors on my Arduino (heart rate, speed & power).

Thank you so much!

Kind regards,
Jerome

**Comment by brodykenrick** [comment]
G'day Jerome,

 Yes - it is possible. I had it setup reading both a hear rate monitor and a cadence/speed monitor with the device I used.

See how I used it at this line of the project I worked on.
https://github.com/brodykenrick/RetroRunnerReadoutEPaper_Arduino/blob/master/RetroRunnerReadout.ino#L474

Cheers,
Brody
